services:
  postgres-container:
    image: postgres:16
    env_file:
      - .env.docker
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:${PGDATA}
    ports:
      - "5431:5432"

  students-api:
    image: student-api:1.0.0
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres-container

volumes:
  postgres-data:
